# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Brèves
    url: post
    weight: 20
  - name: Événements
    url: event
    weight: 40
  - name: Contact
    url: contact
    weight: 999
  - name: Organisation
    url: organisation
    weight: 50
  - identifier: gts
    name: Les groupes de travail
    weight: 50
  - parent: gts
    name: GT-AS
    url: gts/gt-as
    weight: 50
  - parent: gts
    name: GT-GDMM
    url: gts/gt-gdmm
    weight: 51
  - identifier: journees
    name: Journées
    weight: 71
  - parent: journees
    name: Plénières
    url: plenieres
    weight: 71
  - name: Actions
    url: actions
    weight: 70
  - name: Club  industriel
    url: club-industriel
    weight: 70
